db:
    build: db
    restart: always
mq:
    build: mq
    restart: always
    ports:
    - "127.0.0.1:4369:4369"
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"
    expose:
    - "15672"
web:
    build: web-ui
    restart: always
    ports:
    - "127.0.0.1:1337:1337"
    expose:
    - "1337"
    links:
    - db:db
    - mq:mq
    volumes:
    - ./tools:/estiwork/tools
    environment:
      NODE_ENV: development

    



